### ISSUE TITLE
Human agents not recognizing the presence of the Robot

### ISSUE THREAD

**Issue by SadeepRathnayaka** [robotics-upo/hunav_sim#2]
When using the provided Gazebo wrapper, I encountered some unusual behavior in the example Gazebo world. Specifically, pedestrians sometimes pass through the robot (the green-colored man defined as the robot in this example) without acknowledging its presence. This issue does not occur if I change the agent behavior to "Impassive." **For every other reaction**, the crowd fails to notice the robot.

Additionally, there are certain objects in the Gazebo world that the pedestrians do not recognize as obstacles, resulting in them walking through these objects. I am uncertain whether these issues are avoidable or if they are still under development. 

I have added two screenshots for the reference.

1_Screenshot: The agent does not recognize the box which is in the cafe world ( this box is already in the cafe.world, **it has not been added separately to the world like cafe_table** ), as a collision object. The agent will go through that object.

2_Screenshot: The green person is the robot. Other agent does not recognize the presence of the robot. When the agent's behavior parameter changes to "Impassive" then the people will avoid the robot treating the robot as a collision object. **That is the only time people avoid the robot.**

![1_Screenshot](https://github.com/robotics-upo/hunav_sim/assets/129789427/8b54289b-fd2d-46f9-9f78-769bc0eb657f)

![2_Screenshot](https://github.com/robotics-upo/hunav_sim/assets/129789427/c84fb60a-4e96-4a7d-8b06-0a45d426d71c)

**Comment by noeperez** [comment]
Hi! 
Regarding the first screenshot, the cafe scenario is a model that includes several elements, like the floor, walls, or the grey box that you show in the image. Moreover, this model is included in the list of models that must be ignored by the agents. This needs be done in order to not colliding with the floor. So, it is normal than the agents can pass through those elements because they are ignored as obstacles. 

Considering your second screenshot, I have fix some errors in the behaviors. In particular, the agents were ignoring the robot when their individual reactions are not active. It is fixed now, so you can pull the changes. Anyway, the models does not use the collision skeletons, so, in some cases, some parts of the bodies can pass through each other even if the repulsive forces are computed properly.

**Comment by SadeepRathnayaka** [comment]
Hi.

Thank you for the assistance. I will close this issue now.
